// Chosen direction: a deterministic, fictional archive that exercises import, browsing,
// filtering, titleless posts, media grids, details, comments, likes, and AI review without
// using any real person's data.
const demoPhotos = [
  "./assets/demo/riverside.png",
  "./assets/demo/bookstore.png",
  "./assets/demo/rain-breakfast.png",
  "./assets/demo/night-train.png",
  "./assets/demo/spring-blossom.png",
  "./assets/demo/seaside.png",
  "./assets/demo/museum-blue.png",
  "./assets/demo/autumn-bus.png",
  "./assets/demo/first-film.png",
];

const photoSet = (count, offset = 0) => Array.from({ length: count }, (_, index) => demoPhotos[(index + offset) % demoPhotos.length]);

export const demoArchive = {
  id: "demo-archive-2025",
  isDemo: true,
  profileName: "林屿的空间（演示）",
  importedAt: "2025年8月28日 19:30",
  range: "2019—2025",
  entries: [
    {
      id: "post-2025-riverside",
      type: "post",
      date: "2025-08-17T19:42:00+08:00",
      displayDate: "2025年8月17日 19:42",
      text: "傍晚沿着江边慢慢走，风里已经有一点秋天的味道。没有特意拍日落，回头时才发现整条路都被染成了金色。",
      location: "武汉 · 汉口江滩",
      images: photoSet(2, 0),
      likes: ["周沫", "阿程", "苏禾", "小芮", "乔乔"],
      comments: [
        { name: "周沫", text: "照片看起来好舒服，下次一起走。" },
        { name: "阿程", text: "最近傍晚确实没那么热了。" },
      ],
    },
    {
      id: "album-2025-seaside",
      type: "album",
      date: "2025-05-03T21:16:00+08:00",
      displayDate: "2025年5月3日 21:16",
      title: "海边的两天",
      text: "挑了 18 张照片留在这个相册里。最喜欢清晨空荡荡的栈道，还有傍晚被风吹乱的云。",
      location: "青岛 · 小麦岛",
      mediaCount: 18,
      images: photoSet(18, 5),
      likes: ["苏禾", "闻舟", "小芮", "周沫"],
      comments: [{ name: "小芮", text: "第三张海面反光太漂亮了。" }],
    },
    {
      id: "post-2025-bookstore",
      type: "post",
      date: "2025-02-14T16:08:00+08:00",
      displayDate: "2025年2月14日 16:08",
      text: "在旧书店翻到一本 1998 年出版的地图册。纸张已经泛黄，城市的边界也和现在完全不同。",
      location: "武汉 · 昙华林",
      images: photoSet(3, 1),
      likes: ["阿程", "乔乔", "闻舟"],
      comments: [{ name: "闻舟", text: "这种偶遇比专门去找更有意思。" }],
    },
    {
      id: "journal-2024-year-end",
      type: "journal",
      date: "2024-12-31T23:08:00+08:00",
      displayDate: "2024年12月31日 23:08",
      title: "把这一年折好收起来",
      text: "这一年并没有发生想象中的大转折，但我学会了把复杂的事情拆小，也重新捡起了搁置很久的阅读。普通的一年，因为认真生活而变得具体。",
      likes: ["周沫", "苏禾", "阿程", "小芮", "闻舟", "乔乔"],
      comments: [
        { name: "苏禾", text: "普通但具体，这个总结很喜欢。" },
        { name: "周沫", text: "新的一年继续慢慢来。" },
      ],
    },
    {
      id: "post-2024-rain",
      type: "post",
      date: "2024-09-21T10:34:00+08:00",
      displayDate: "2024年9月21日 10:34",
      text: "雨下了一整夜，早上索性晚一点出门。热豆浆、刚出炉的面包和窗外被雨洗亮的树，组成了今天的开场。",
      location: "家附近",
      images: photoSet(4, 2),
      likes: ["乔乔", "小芮", "周沫"],
      comments: [],
    },
    {
      id: "album-2024-museum",
      type: "album",
      date: "2024-04-06T18:25:00+08:00",
      displayDate: "2024年4月6日 18:25",
      title: "博物馆里的蓝",
      text: "从青花瓷到矿物颜料，把今天见到的蓝色单独整理成了一组照片。",
      location: "南京博物院",
      mediaCount: 12,
      images: photoSet(12, 6),
      likes: ["闻舟", "苏禾", "阿程", "乔乔"],
      comments: [{ name: "苏禾", text: "这个相册的颜色整理得很妙。" }],
    },
    {
      id: "post-2023-night-train",
      type: "post",
      date: "2023-10-04T23:47:00+08:00",
      displayDate: "2023年10月4日 23:47",
      text: "窗外偶尔闪过亮着灯的小站。耳机里刚好播到大学时常听的歌，一下子想起很多没有拍照的片段。",
      images: photoSet(6, 3),
      likes: ["阿程", "周沫", "小芮", "闻舟"],
      comments: [{ name: "阿程", text: "夜车和旧歌总是很会让人想起以前。" }],
    },
    {
      id: "journal-2023-moving",
      type: "journal",
      date: "2023-06-18T20:10:00+08:00",
      displayDate: "2023年6月18日 20:10",
      title: "搬家之后的第一周",
      text: "新住处还没有完全收拾好，但书已经先摆上了架。开始熟悉楼下的早餐店、傍晚的光线，以及从地铁口回家的那段路。",
      likes: ["周沫", "苏禾", "乔乔"],
      comments: [{ name: "乔乔", text: "等你收拾好去暖房。" }],
    },
    {
      id: "post-2022-project",
      type: "post",
      date: "2022-11-12T00:26:00+08:00",
      displayDate: "2022年11月12日 00:26",
      text: "连续改了四版的项目终于交出去了。关掉电脑之后，房间突然安静得有点不习惯。先睡一觉，明天再庆祝。",
      images: photoSet(1, 5),
      likes: ["阿程", "苏禾", "小芮", "周沫", "闻舟"],
      comments: [
        { name: "小芮", text: "辛苦了，明天必须吃顿好的。" },
        { name: "阿程", text: "第四版最稳，值得庆祝。" },
      ],
    },
    {
      id: "album-2022-autumn",
      type: "album",
      date: "2022-10-30T17:52:00+08:00",
      displayDate: "2022年10月30日 17:52",
      title: "秋天只是路过",
      text: "银杏、路边摊、公交车窗和傍晚六点的天色。一共 24 张，都是这个短暂秋天的证据。",
      location: "成都",
      mediaCount: 24,
      images: photoSet(24, 7),
      likes: ["周沫", "乔乔", "苏禾", "闻舟"],
      comments: [{ name: "周沫", text: "最后一张公交车窗很有电影感。" }],
    },
    {
      id: "post-2022-spring",
      type: "post",
      date: "2022-03-06T15:31:00+08:00",
      displayDate: "2022年3月6日 15:31",
      text: "出门买菜时绕了远路，在街角看见一整面开花的树。春天没有通知谁，但还是准时来了。",
      images: photoSet(9, 4),
      likes: ["小芮", "苏禾", "阿程"],
      comments: [],
    },
    {
      id: "journal-2021-graduation",
      type: "journal",
      date: "2021-06-25T22:18:00+08:00",
      displayDate: "2021年6月25日 22:18",
      title: "毕业之后",
      text: "最后一次从宿舍楼下经过，门口的树和四年前几乎一样。我们说了很多以后要常见面的话，也知道生活会把大家带去不同的方向。",
      likes: ["阿程", "周沫", "苏禾", "小芮", "乔乔", "闻舟"],
      comments: [
        { name: "阿程", text: "照片和人都要记得备份。" },
        { name: "周沫", text: "会再见的。" },
      ],
    },
    {
      id: "post-2021-library",
      type: "post",
      date: "2021-04-13T21:05:00+08:00",
      displayDate: "2021年4月13日 21:05",
      text: "今天才认真听清闭馆前放的那段音乐。大家开始收电脑、合上书，像一场每天都会重复的谢幕。",
      likes: ["闻舟", "乔乔"],
      comments: [{ name: "闻舟", text: "以后听到那段旋律肯定还会想起来。" }],
    },
    {
      id: "album-2020-winter",
      type: "album",
      date: "2020-12-20T14:44:00+08:00",
      displayDate: "2020年12月20日 14:44",
      title: "窗边的一整个冬天",
      text: "把今年在窗边拍的天空放到了一起，从很浅的灰到偶尔出现的橙色。",
      mediaCount: 16,
      images: photoSet(16, 2),
      likes: ["苏禾", "周沫", "小芮"],
      comments: [{ name: "苏禾", text: "同一个窗口也能看到这么多变化。" }],
    },
    {
      id: "post-2019-first-camera",
      type: "post",
      date: "2019-07-09T18:02:00+08:00",
      displayDate: "2019年7月9日 18:02",
      text: "冲出来的照片有几张过曝，还有一张不小心拍到了鞋尖。但第一次等一卷照片出来，还是很开心。",
      location: "学校附近",
      images: photoSet(12, 8),
      likes: ["阿程", "乔乔", "周沫"],
      comments: [{ name: "乔乔", text: "鞋尖那张反而最像夏天。" }],
    },
  ],
  review: {
    headline: "你记录最多的，不是大事件，而是生活开始变得具体的瞬间。",
    summary: "从 2019 到 2025，演示档案里的表达逐渐从校园与朋友，转向城市、工作和安静的日常。照片变多了，文字变短了，但对季节和光线的关注一直没有改变。",
    themes: [
      { name: "城市漫游", count: 5, note: "江边、书店、博物馆和回家的路" },
      { name: "季节与光线", count: 4, note: "尤其偏爱傍晚、雨天和短暂的秋天" },
      { name: "学习与工作", count: 3, note: "从毕业到完成重要项目" },
      { name: "朋友的回应", count: 13, note: "周沫与阿程出现在最多互动中" },
    ],
    moments: [
      { year: "2025", text: "开始主动保存城市里的微小发现。" },
      { year: "2023", text: "搬家成为生活重心变化的分界点。" },
      { year: "2021", text: "毕业日志拥有最多评论与共同回忆。" },
      { year: "2019", text: "第一卷胶片开启了持续多年的影像记录。" },
    ],
  },
};

export function getDemoStats(archive = demoArchive) {
  const totals = archive.entries.reduce((result, entry) => {
    result.total += 1;
    result[entry.type] += 1;
    result.comments += entry.comments.length;
    result.likes += entry.likes.length;
    return result;
  }, { total: 0, post: 0, journal: 0, album: 0, comments: 0, likes: 0 });
  return totals;
}
